[project]
name = "nlp-diagram-creator"
version = "0.1.0"
description = "LLM-based diagram creator"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "httpx",
    "diagrams",
    "python-dotenv",
]
